# Custom lower threshold for /var (houses Docker, Plex, logs)

    template: disk_space_usage_var
          on: disk.space
       class: Utilization
        type: System
   component: Disk
chart labels: mount_point=/var
        calc: $used * 100 / ($avail + $used)
       units: %
       every: 1m
        warn: $this > (($status >= $WARNING ) ? (70) : (75))
        crit: ($this > (($status == $CRITICAL) ? (85) : (90))) && $avail < 5
       delay: up 1m down 15m multiplier 1.5 max 1h
     summary: Disk /var space usage
        info: Space utilization of /var - warn at 75%, crit at 90%
          to: sysadmin
