server {
    listen 443 ssl;
    server_name metro.sba.camerontora.ca;

    ssl_certificate /etc/letsencrypt/live/camerontora-services/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/camerontora-services/privkey.pem;

    location / {
        proxy_pass http://host.docker.internal:8081;
        proxy_http_version 1.1;

        # WebSocket support (Metro hot reload)
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 86400;
    }
}
